version: "3.1"
services:
    webserver:
      image: nginx:alpine
      container_name: joinvix-webserver
      working_dir: /var/www/html/
      volumes:
          - .:/var/www/html/
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      networks:
        - mrede

    php-fpm:
      image: php:7.2-fpm
      container_name: joinvix-php-fpm
      working_dir: /var/www/html/
      volumes:
        - .:/var/www/html/
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      networks:
        - mrede
networks: 
    mrede: